### ISSUE TITLE
Revisit the Browbeat and Grafana integration

### ISSUE THREAD

**Issue by mbruzek** [redhat-performance/tripleo-quickstart-scalelab#38]
David Wilson asked me about the Graphana dashboards for the scale-ci (Alderaan hardware). We had not run the Browbeat job in over a week, so I [ran the Browbeat Jenkins job](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/scale-ci_install_Browbeat/8/consoleFull) and it was successful.

After talking with @akrzos he indicated that this job only installs collectd agent and ships data to graphite. There was more we can do with Browbeat but that involves installing Browbeat and [deploying the dashboards](https://github.com/redhat-performance/McCloud/blob/master/roles/028-browbeat-deploy-grafana-dashboards/tasks/main.yml). We do not want to add a lot of time or complexity to the automation at this time, and do not want to fail the scale-ci automation if the Browbeat job fails.

Revisit the Browbeat work and discuss what needs to be done going forward. Prioritize that work with the other issues in this repository.

**Comment by akrzos** [comment]
The Dash-boarding portion of Browbeat would be valuable to have however the most recent update to the dashboards now requires Browbeat be installed since the dashboards depend on GrafYaml.  We can actually get this installed outside of Browbeat install for something faster than a full Browbeat install.
